---
- name: Output Automation Controller Configs
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Assert defined variables
      ansible.builtin.assert:
        that:
          - aap_hostname is defined
          - aap_username is defined
          - aap_password is defined
        fail_msg: "You must define aap_hostname, aap_username, and aap_password in vars.yml."

    - name: "Setup authentication (block)"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: aap_oauthtoken is not defined
      tags:
        - always
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ aap_hostname }}/api/gateway/v1/tokens/"
            user: "{{ aap_username }}"
            password: "{{ aap_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ aap_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            aap_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            aap_oauthtoken_url: "{{ authtoken_res.json.url }}"
      
        - name: Recursively remove output directory
          ansible.builtin.file:
            path: "{{ output_path }}"
            state: absent

  roles:
    - infra.aap_configuration_extended.filetree_create

  post_tasks:
    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ aap_hostname }}{{ aap_oauthtoken_url }}"
        user: "{{ aap_username }}"
        password: "{{ aap_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 204
      when: aap_oauthtoken_url is defined

    - name: Disable schedules, only if schedules are exported
      ansible.builtin.include_tasks:
        file: "tasks/schedules.yaml"
      with_first_found:
        - files:
          - "{{ output_path }}/schedules.yaml"
          skip: True
      when: disable_schedules

    - name: Read hosts.yaml file into variable if present
      ansible.builtin.include_tasks:
        file: "tasks/hosts.yaml"
      with_first_found:
        - files:
          - "{{ output_path }}/hosts.yaml"
          skip: True

    - name: Remove lines containing "..."
      ansible.builtin.lineinfile:
        path: "{{ output_path }}/controller_job_templates.yaml"
        regexp: "\\.\\.\\."
        state: absent
...
